#download base image of ubuntu having java8
FROM harisekhon/ubuntu-java
MAINTAINER prashant
COPY . java-codes
WORKDIR /java-codes 
CMD java -jar Demo3MavenJDBC-0.0.1-SNAPSHOT-jar-with-dependencies.jar
